commands (MP)
momo5502/open-iw5 pull request #26
Opened 2022-02-18 14:28 UTC by skkuull

Hey, i have added some useful commands to multiplayer like god, demigod, noclip and ufo
and generic commands like commandDump, quit and crash(credit to geekidos)
Maybe in future i'll add the same but for singleplayer.

TODO: add commands_sv?

2022-02-19 18:15 UTC, mjkzy requested changes
should format all these brackets to not look like ass

2022-02-19 18:16 UTC, mjkzy commented
if ur leaving TODOs in here, its a draft then...?

2022-02-19 19:55 UTC, skkuull commented
> should format all these brackets to not look like ass

like add an void for each game mode?
Sidenote: the only thing matters here how do they look in game.

2022-02-19 19:57 UTC, mjkzy commented
> > should format all these brackets to not look like ass
> 
> like add an void for each game mode? Sidenote: the only thing matters here how do they look in game.

refer to how this adds commmands. this is a a more recent project of momo's
https://github.com/XLabsProject/s1x-client/blob/36b11f260acacc6bb7954b33a4d534d2775e5fda/src/client/component/command.cpp#L245)

2022-02-19 20:04 UTC, skkuull commented
Yep, Good idea, i was thinking in the same way, but when i saw dedi's stuff i just made an if statement for specific game mode like mp and sp
also, i made this on rush tho didn't focus much things

2022-03-10 10:02 UTC, diamante0018 requested changes
Format the entire code as well.

2022-03-10 10:02 UTC, diamante0018 commented on src/module/command.cpp
> +	command::add("quit", [](const std::vector<std::string>& callback)
what are you thinking when adding a command that already exists? want to crash a client instead of quitting?

2022-03-10 10:02 UTC, diamante0018 commented on src/module/command.cpp
> +	command::add("crash", [](const std::vector<std::string>& args)
There is no need for this command to exist

2022-03-10 10:02 UTC, diamante0018 commented on src/module/command.cpp
> +void mp_commands()
This is wrong.
You must use setup a clientcommand handler like it's done on s1x.
I'm sure you can find it for both mp and dedi binary

2022-03-10 10:05 UTC, diamante0018 commented on src/module/command.cpp
> +
Random newlines

2022-03-10 12:33 UTC, skkuull commented on src/module/command.cpp
> +	command::add("quit", [](const std::vector<std::string>& callback)
Does it exists?, Also yea this is crashing which will cause issues

2022-03-10 12:33 UTC, skkuull commented on src/module/command.cpp
> +	command::add("crash", [](const std::vector<std::string>& args)
Indeed

2022-03-10 12:34 UTC, diamante0018 commented on src/module/command.cpp
> +	command::add("quit", [](const std::vector<std::string>& callback)
if it doesn't add com_quit_f to game.cpp and call that

2022-03-10 12:35 UTC, skkuull commented on src/module/command.cpp
> +	command::add("quit", [](const std::vector<std::string>& callback)
I believe it doesn't exists, gonna look up to that

2022-03-10 12:43 UTC, diamante0018 commented on src/module/command.cpp
> +	command::add("quit", [](const std::vector<std::string>& callback)
on the dedi binary it already exists. on sp/mp it doesn't.
it's 0x05556b0 on the mp binary, 0x04f48b0 on the sp binary

2022-03-10 12:53 UTC, skkuull commented on src/module/command.cpp
> +	command::add("quit", [](const std::vector<std::string>& callback)
i thought it was exe_serverquit

2022-03-10 13:08 UTC, skkuull commented on src/module/command.cpp
> +	command::add("quit", [](const std::vector<std::string>& callback)
it doesn't seem to work, nothing happens when command is executed

2022-03-10 13:15 UTC, diamante0018 commented on src/module/command.cpp
> +	command::add("quit", [](const std::vector<std::string>& callback)
![Screenshot 2022-03-10 131355](https://user-images.githubusercontent.com/37080671/157669100-dd496c0f-263c-4395-a136-b192b9883ddd.png)
I guess it's not quit_f? the function is there. this is how I found it. by xexref of exe_server_killed or quit

2022-03-10 13:21 UTC, skkuull commented on src/module/command.cpp
> +	command::add("quit", [](const std::vector<std::string>& callback)
I mean it looks like clean to me, it should be this address but for some reason its not working

2022-03-10 15:13 UTC, diamante0018 commented on src/module/command.cpp
> +	command::add("quit", [](const std::vector<std::string>& callback)
Well, anyway you are focusing on not a super important command. I'd focus on adding the client command handler.
You can basically copy paste the code from iw4x or s1x.
the quit command at the worst can be an ExitProcess(0);

2022-03-10 16:24 UTC, diamante0018 requested changes

2022-03-10 16:24 UTC, diamante0018 commented on src/module/command.cpp
> +			game::native::cmd_function_s* cmd = (game::native::cmd_functions);
You have a crash right here. Because you have only specified the mp address in game.cpp you will crash here if you run the command from sp, dedi. should be addressed before pr is merged.

2022-03-10 16:25 UTC, diamante0018 commented on src/game/structs.hpp
> +		struct cmd_function_s
cmd_function_t is already defined in the structs header file lol

2022-03-10 18:09 UTC, momo5502 reviewed
Great review by @diamante0018, I have nothing to add

2022-03-11 00:27 UTC, skkuull commented
looks like @diamante0018 already done the job in his pr, no need for this anymore.

2022-03-11 00:27 UTC, closed without merging